export const THEME = {
    MAIN_BUTTON: "#1976d2",
    MAIN_TEXT_BUTTON: "#FFFFFF",
    SECONDARY_BUTTON: "#81C784",
    SECONDARY_TEXT_BUTTON: "black",
    MENU_BACKGROUND: "#FFFFFF",
    THEME_BACKGROUND: "#F3F5F7",
    CARD_BACKGROUND: "#FFFFFF",
    CARD_BORDER: "#E0E0E0",
    MENU_TEXT: "#074C31",
    ACTIVE_MENU_BG: "#2E7D32"
}

